modLoader="javafml"
loaderVersion="[2,)"
license="MIT"

[[mods]]
modId="walkietalkie"
version="${mod_version}"
displayName="Walkie-Chat"
displayURL="https://github.com/Theus452/Walkie-Chat"
authors="Theus452"
description='''
Walkie-Talkie Mod
'''

[[dependencies.walkietalkie]]
modId="neoforge"
type="required"
versionRange="[21,)"
ordering="NONE"
side="BOTH"

[[dependencies.walkietalkie]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[mixins]]
config="walkietalkie.mixins.json"
